# Generated by Django 4.1.13 on 2024-03-27 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('post_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публикации')),
            ],
        ),
    ]
